version: '2'
services:
    oltgenerator:
        build:
            context: .
            dockerfile: oltgenerator
        logging:
            driver: fluentd
            options:
                #fluentd-address: "localhost:24224"
                fluentd-async-connect: "true"
                tag: "docker"
        links:
            - fluentd:fluentd
    fluentd:
        build:
            context: .
            dockerfile: fluentd
        ports:
            - "24224:24224"
